baseurl = "https://yii.im/"
languageCode = "zh-CN"
title = "yii.im"
theme = "vec"
paginate = 20
disqusShortname = "yiiim"
googleAnalytics = "UA-57408564-1"
  
[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "posts"
    weight = 1
    url = "/posts"
  [[menu.main]]
    name = "about"
    weight = 0
    url = "/about"
    
[params]
  Keywords = "ichou, ruby, rails"
  Description = ""
  Avatar = "/avatar.jpeg"
  SelfIntro = "Just a worm, seek for true, live in shadow, no more..." 
  
  Email = "yiichou@gmail.com"
  GithubID = "yiichou"
  TwitterID = "IamIchou"
  GoogleplusID = "106025147843011494846"